### PR TITLE
Added High Score feature and improved the code structure.

### PR DESCRIPTION
**Pull request by BirajCoder**
Resolved Issue #39 
- Added best moves and best time feature for Hard Mode
- There were two same index.js and styles.css files in the repo, removed the unnecessary file and linked the correct file
- Removed an unwanted CSS class from the CSS file
- Added Template Strings (ex: \`Value of var1 = ${var1}\`) instead of normal strings in the final Add Stats Function.
- Changed the congratulations message of "Time to complete:" to "Time taken:"

### CODE REVIEW

**Comment by BirajCoder** [comment]
Image for the first play in hard mode in a browser
hard_1st
.

**Comment by BirajCoder** [comment]
Do you want me to add different high scores for easy and medium? Cause, if I use the same high score for easy medium and hard, easy will always have the best time and best moves.

**Comment by ANSHIKA1806** [comment]
> Do you want me to add different high scores for easy and medium? Cause, if I use the same high score for easy medium and hard, easy will always have the best time and best moves.

Yes add different high scores for all.

**Comment by BirajCoder** [comment]
Background Fixed:
image

Will Add the high scores of other modes soon.

**Pull request merged**
