### PR TITLE
Makeover README.md

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## Changes/Addition
- Proper Fonts
- Proper Language
- ScreenShots (Game)
- Logos for the programming language used
- Text Hyperlinks Addition

Fix - #9 
@ANSHIKA1806

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
#14

**Comment by Pradumnasaraf** [comment]
Pease check and merge @ANSHIKA1806 :)

**Comment by ANSHIKA1806** [comment]
@Pradumnasaraf Fork this repository again and then paste the changes then make another PR.
This one has some conflicts.

**Comment by Pradumnasaraf** [comment]
ok

**Pull request merged**
